import {
  Clock,
  Shield,
  ShieldCheck,
  Award,
  Sparkles,
  CheckCircle2,
  BadgeCheck,
  Star,
  Heart,
  ThumbsUp,
  Users,
  User,
  UserCircle,
  UserCheck,
  ScanLine,
  Handshake,
  HandHeart,
  HeartHandshake,
  Zap,
  Rocket,
  Timer,
  Gauge,
  Target,
  Flag,
  Scale,
  Gavel,
  FileText,
  FileCheck,
  ClipboardCheck,
  IdCard,
  Fingerprint,
  Lock,
  Eye,
  Smile,
  Phone,
  Mail,
  MapPin,
  Home,
  Building2,
  Landmark,
  Globe,
  Coins,
  Gift,
  Leaf,
  Sun,
  Accessibility,
  Baby,
  // Dipakai kartu indeks PPID (lib/ppid-informasi.ts).
  BookOpen,
  CalendarDays,
  ClipboardList,
  Wallet,
  UserPlus,
  Printer,
  ScrollText,
  Book,
  type LucideIcon,
} from 'lucide-react';

/**
 * Ikon yang tersedia untuk dipilih di editor konten (mis. kartu Maklumat).
 * Disimpan sebagai NAMA (string) di database; komponen publik memetakannya
 * kembali ke komponen ikon lewat ICON_MAP.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  BookOpen,
  CalendarDays,
  ClipboardList,
  Wallet,
  UserPlus,
  Printer,
  ScrollText,
  Book,
  Clock,
  Shield,
  ShieldCheck,
  Award,
  Sparkles,
  CheckCircle2,
  BadgeCheck,
  Star,
  Heart,
  ThumbsUp,
  Users,
  User,
  UserCircle,
  UserCheck,
  ScanLine,
  Handshake,
  HandHeart,
  HeartHandshake,
  Zap,
  Rocket,
  Timer,
  Gauge,
  Target,
  Flag,
  Scale,
  Gavel,
  FileText,
  FileCheck,
  ClipboardCheck,
  IdCard,
  Fingerprint,
  Lock,
  Eye,
  Smile,
  Phone,
  Mail,
  MapPin,
  Home,
  Building2,
  Landmark,
  Globe,
  Coins,
  Gift,
  Leaf,
  Sun,
  Accessibility,
  Baby,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

/** Ambil komponen ikon dari nama; fallback ke ikon default bila tak dikenal. */
export function getIcon(name: string | undefined, fallback: LucideIcon = Sparkles): LucideIcon {
  return (name && ICON_MAP[name]) || fallback;
}
